---
title: "L'assurance-maladie obligatoire suisse dans l'impasse. Une analyse du compromis socio-politique derrière la Loi fédérale sur l’assurance maladie (LAMal)"
subtitle: "Annexe"
author: 
  - "Celâl Güney"
  - "Gaia Valenti"
format: 
  html: 
    theme:
      light: flatly
      dark: darkly
    toc: true
  pdf:
    pdf-engine: lualatex
  docx: default
editor: visual
execute: 
  eval: true
  warning: false
  message: false
  echo: false 
draft: false
lang: fr
---

```{r set up}
#| echo: false
#| message: false
#| warning: false
rm(list = ls())

options(scipen = 100, digits = 4)
library(tidyverse)
library(readr)
library(quarto)
votation_allegement_prime <- read_delim("data/votation_allegement_prime.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)
```

## Swissvotes

```{r tableau votation}
#| echo: false
#| message: false
#| warning: false
#| eval: true

library(readr)
swissvotes <- read_delim("data/swissvotes.csv", 
    delim = ";", escape_double = FALSE, col_types = cols(d1e3 = col_double()), 
    trim_ws = TRUE)


swissvotes2 <- 
swissvotes %>% 
  filter(d1e3 %in% c("10.24", "10.11")) %>% 
  dplyr::select(datum, titel_kurz_f, annahme, `volkja-proz`) %>% 
  rename(
    Date = "datum",
    Votation = "titel_kurz_f",
    `Résultat` = "annahme",
    `% Oui` = "volkja-proz"
  )

library(gt)

swissvotes_table <- 
swissvotes2 %>% 
  gt()


#gtsave(swissvotes_table, "table_votations.png", expand = 15)

swissvotes_table

```

## Faits stylisés

```{r set up faits stylises}
#| echo: false
#| message: false
#| warning: false


library(readxl)
library(tidyverse)

data_final_am <- read_excel("data_final_am.xlsx", 
    sheet = "graphique 1") %>% 
  pivot_longer(
    cols = 2:15,
    names_to = "variable",
    values_to = "value"
  )





```

```{r graphique IPAM}
#| echo: false
#| message: false
#| warning: false



plot1 <- 
data_final_am %>% 
  filter(variable %in% c("indice_cout_sante_hab100", "salaire_reel100", "salaire_nominal100", "pib_reel_100", "ipam_total")) %>% 
  ggplot(aes(x = Year, y = value, color = variable, linetype = variable))+
  geom_line(size = 1)+
  labs(y = "1999 = 100",
       x = "",
       title = "Évolution de l'indice des primes d'assurance-maladie")+
  theme_minimal()+
  scale_color_discrete(labels = c("Coûts de la santé par habitants",
                                  "Indice des primes d'assurance-maladie",
                                  "PIB réel",
                                  "Indice des salaires nominaux",
                                  "Indice des salaires réels"))+
  scale_linetype_discrete(labels = c("Coûts de la santé par habitants",
                                    "Indice des primes d'assurance-maladie",
                                     "PIB réel",
                                     "Indice des salaires nominaux",
                                     "Indice des salaires réels"))+
  theme(legend.position = "bottom",
        legend.title = element_blank(),
        text = element_text(size = 11.6))+
  guides(color = guide_legend(nrow = 2)) 

plot1

#ggsave("plot_ipam.jpg", plot1)

```

```{r graph faits stylises 2}

#| echo: false
#| message: false
#| warning: false


library(viridis)
library(paletteer)
library(cowplot)
library(gridExtra)

dep_quantiles <- data_final_am <- read_excel("data_final_am.xlsx", 
    sheet = "graphique2", skip = 3) %>% 
  pivot_longer(cols = -1)

plot2 <- 
dep_quantiles %>% 
  ggplot(aes(x = annee, y = value, fill = name))+
  geom_col(position = "dodge", color = "white")+
  theme_minimal()+
  labs(x = "",
       y = "Pourcentage du revenu disponible brut",
       title = "Dépense des ménages suisses pour les primes de l'assurance-maladie de base")+
  scale_fill_paletteer_d("nationalparkcolors::Acadia",
                         name = "Quintile")+
  theme(text = element_text(size = 11))



#ggsave("graph_budget_menages.png", plot2)


#grid.arrange(plot1, plot2, ncol = 2)

```

```{r graph 3 financement sante}

#| echo: false
#| message: false
#| warning: false


library(readr)
library(ggtext)
library(ggrepel)

financement_sante <- read_csv("data/financement_sante.csv")


financement_sante2 = financement_sante %>% 
  pivot_longer(cols = -1) %>% 
  rename(annee = "Label_FR") %>% 
  group_by(annee) %>% 
  mutate(
    total = sum(value),
  ) %>% 
  group_by(annee, name) %>% 
  mutate(
    part = value/total
  )


graph_financement <- 
financement_sante2 %>% 
  ggplot()+
  aes(x = annee, y = part, color = name)+
  geom_line(size = 1.2)+
  scale_y_continuous(labels = scales::percent)+
  scale_color_paletteer_d("ggthemes::Classic_10")+
  theme_minimal()+
  geom_label_repel(
    data = financement_sante2 %>% filter(annee == 2023),
    aes(label = name, x = annee, y = part),
    direction = "y",
    nudge_y = 0.001,
    nudge_x = 10,
    size = 2.8
  )+
  theme(legend.position = "none")+
  labs(x = "", y = "",
       subtitle = "Financement du système de santé selon la source")

graph_financement
#ggsave("graph_financement.png", graph_financement)  
  
```

```{r graph subventions lamal}
library(readxl)
subventions <- read_excel("data_final_am.xlsx", 
    sheet = "graphique3") %>% 
  pivot_longer(cols = -1)

plot_subvention1 <- 
subventions %>% 
  filter(
    name %in% c("Subventions par ménage (francs)", "Taux de bénéficiaires (%)")
  ) %>% 
  ggplot(aes(x = annee, y = value))+
  geom_line()+
  theme_minimal()+
  facet_wrap(~name, scales = "free_y")+
  theme(text = element_text(size = 16))+
  labs(x = "", y = "")

plot_subventions2 <- 
subventions %>% 
  filter(name %in% c("Subventions selon la LAMal par ménage (en francs)", "Primes moyennes par assuré")) %>% 
  ggplot(aes(x = annee, y = value, color = name))+
  geom_line()+
  theme_minimal()+
  theme(legend.position = "bottom",
        legend.title = element_blank())+
  labs(x = "", y = "1996 = 100",
       subtitle = "Évolution des subventions et des primes")+
  theme(text = element_text(size = 16))

plot2 <- 
dep_quantiles %>% 
  ggplot(aes(x = annee, y = value, fill = name))+
  geom_col(position = "dodge", color = "white")+
  theme_minimal()+
  labs(x = "",
       y = "Pourcentage du revenu disponible brut",
       title = "Dépense des ménages suisses pour les primes de l'assurance-maladie de base")+
  scale_fill_paletteer_d("nationalparkcolors::Acadia",
                         name = "Quintile")+
  theme(text = element_text(size = 16))

plot_subventions3 <- grid.arrange(arrangeGrob(plot_subvention1, plot_subventions2, ncol = 1), plot2, ncol = 2)

#ggsave("graph_subventions.png", plot_subventions3, width = 60, height = 30, units = "cm")

plot_subventions3

```

## Votation

```{r votation merging}
#| echo: false
#| message: false
#| warning: false


library(tidyverse)
library(readr)

votations2024 <- read_excel("data/votations2024.xlsx", 
    col_types = c("numeric", "text", "numeric", 
        "numeric"))

afc_chiffrescles_2022 <- read_excel("data/afc_chiffrescles_2022.xlsx", 
    sheet = "Gemeinden - Communes")


data = votations2024 %>% 
  left_join(afc_chiffrescles_2022, by = c("Gemeindenummer" = "Gemeindenummer\r\nCode commune"))





```

```{r maps}

#| echo: false
#| message: false
#| warning: false


library(BFS)
library(ggplot2)
library(sf)
library(mapview)

communes_sf <- bfs_get_base_maps(geom = "polg", date = "20240101")
communes_sf$id = as.numeric(communes_sf$id)
datamap = data %>% 
  left_join(communes_sf, by = c("Gemeindenummer" = "id"))

efas_votation_commune <- read_excel("data/efas_votation_commune.xlsx", 
    skip = 4)

datamap2 = efas_votation_commune[, c(1, 3, 4, 13)] %>% 
  left_join(datamap, by = c("No commune" = "Gemeindenummer")) %>% 
  rename("efas_oui" = `Oui en %`)

datamap %>% 
  ggplot()+ 
  geom_sf(aes(geometry = geometry, fill = allegement_primes_oui))+
  theme_void()+
  scale_fill_viridis_b()+
  theme(legend.position = "bottom") 

datamap2 %>% 
  ggplot()+ 
  geom_sf(aes(geometry = geometry, fill = efas_oui))+
  theme_void()+
  scale_fill_viridis_c(option = "turbo", direction = -1)+
  theme(legend.position = "bottom") 


library(biscale)

biclass = bi_class(datamap2, x = median_reinka, y = efas_oui, style = "quantile", dim = 3, na_rm = TRUE)

bimap = 
ggplot() +
  geom_sf(data = biclass, mapping = aes(geometry = geometry, fill = bi_class), color = "white", size = 0.1, show.legend = F) +
  bi_scale_fill(pal = "GrPink", dim = 3) +
  bi_theme(base_size = 10)+
  labs(
    title = "Votation sur le financement uniforme des prestations de santé",
    caption = " Pour chaque commune, le pourcentage de oui à la votation de novembre 2024 
    sur l'uniformation du financement des prestations de santé.
    Le revenu médian correspond à la médiane du revenu équivalent net en 2022 (en franc). Source: OFS"
  )

legend <- bi_legend(pal = "GrPink",
                    dim = 3,
                    xlab = "Revenu médian",
                    ylab = "Oui en %",
                    size = 8)
library(cowplot)

ggdraw() +
  draw_plot(bimap, 0, 0, 1, 1) +
  draw_plot(legend, 0.05, .65, 0.2, 0.2)

```



## Selects panel 2023 Minimum franchise

```{r setup selects2023 panel}
#| echo: false
#| message: false
#| warning: false


rm(list=ls())
library(haven)
library(tidyverse)
library(marginaleffects)
library(sjlabelled)
library(DIGCLASS)

selects2023panel <- haven::read_sav("data/selects2023panel/selects2023panel.sav") #linux

selects2023panel$isco08 = selects2023panel$W1_ISCO08prof_2dig*100

selects2023panel2 = selects2023panel %>% 
  rename(
    "assurance_maladie_franchise_pour" = W1_f15340f,
    "op_limit_immigration" = W1_f15340b,
    "op_funding_childcare" = W1_f15340c,
    "op_protec_env" = W1_f15340d,
    'op_state_interv' = W1_f15435,
    'op_social_expenses' = W1_f15420,
    'op_eu_integration' = W1_f15425,
    'op_chances_foreigners' = W1_f15440,
    'op_gender_equality' = W1_f15475,
    'op_taxes_high_income' = W1_f15480,
    'op_traditions' = W1_f15485,
    'op_min_wage' = W1_f15815,
    'op_incr_retirementAge' = W1_f15811,
    'probs_vote_plr' = W1_f14400a,
    'probs_vote_centre' = W1_f14400j,
    'probs_vote_ps' = W1_f14400c,
    'probs_vote_udc' = W1_f14400d,
    'probs_vote_verts' = W1_f14400e,
    'probs_vote_vertsliberaux' = W1_f14400f,

  ) %>% 
  mutate(
    income = case_when(
  W1_f28910 == 1  ~ (0+2000)/2,
  W1_f28910 == 2  ~ (2001+3000)/2,
  W1_f28910 == 3  ~ (3001+4000)/2,
  W1_f28910 == 4  ~ (4001+5000)/2,
  W1_f28910 == 5  ~ (5001+6000)/2,
  W1_f28910 == 6  ~ (6001+7000)/2,
  W1_f28910 == 7  ~ (7001+8000)/2,
  W1_f28910 == 8  ~ (8001+9000)/2,
  W1_f28910 == 9  ~ (9001+10000)/2,
  W1_f28910 == 10 ~ (10001+11000)/2,
  W1_f28910 == 11 ~ (11001+12000)/2,
  W1_f28910 == 12 ~ (12001+13000)/2,
  W1_f28910 == 13 ~ (13001+14000)/2,
  W1_f28910 == 14 ~ (14001+15000)/2,
  W1_f28910 == 15 ~ (15001+16000)/2,
  W1_f28910 == 16 ~ (16001+17000)/2,
  W1_f28910 == 17 ~ (17001+18000)/2,
  W1_f28910 == 18 ~ (18001+19000)/2,
  W1_f28910 == 19 ~ (19001+20000)/2,
  W1_f28910 == 20 ~ 20001         
),
income_decile = ntile(income, n = 10),
income_adjusted = income/sqrt(W1_hhsize_sample),
income_adj_decile = ntile(income_adjusted, n = 10),

lr = if_else(W1_f15200 == 98 | is.na(W1_f15200), NA, W1_f15200),

education_ISCED = case_when(
  W1_f21310rec %in% c(1, 2) ~ 1,  # No education, Primary = ISCED 1
  W1_f21310rec == 3        ~ 2,  # Secondary school = ISCED 2
  W1_f21310rec %in% c(4,5) ~ 3,  # Basic vocational, apprenticeship = ISCED 3
  W1_f21310rec %in% c(6,7,8) ~ 4, # Upper secondary specialized, trade, vocational = ISCED 4 
  W1_f21310rec == 9 ~ 5,  # Matu = ISCED 5
  W1_f21310rec == 10 ~ 5,  # Higher vocational education with federal diploma = ISCED 5
  W1_f21310rec == 11 ~ 6,  # College of higher education = ISCED 6
  W1_f21310rec == 12 ~ 6,  # Uni of applied sciences = ISCED 6 (Bachelor level)
  W1_f21310rec == 13 ~ 7,  # University / Federal Institute of Technology = ISCED 7 (Master)
  W1_f21310rec == 14 ~ NA   # other
),

public_sector = if_else(W1_f21700 == 2, 1,
                        if_else(is.na(W1_f21700), 0, 0)),
canton = as_character(W1_canton_sample),
langue = relevel(factor(as_character(W1_munilang_sample)), ref = "German"),
gender = factor(as_label(W1_sex)),

#isco08_4d = isco08_swap(W1_ISCO08prof_2dig, from = 2, to = 3),

main_activity = case_when(
  
  W1_f21400 %in% c(1, 2, 7) ~ 1, # working
  W1_f21400 %in% c(3) ~ 2, # in training/education
  W1_f21400 %in% c(6) ~ 3, # disability
  W1_f21400 %in% c(4, 8) ~ 4, # no paid work
  W1_f21400 %in% c(5) ~ 5 # retired
  
),

work_status = case_when(
  W1_f21500 == 4 ~ 1, # self-employed
  W1_f21500 %in% c(1, 2, 3) ~ 0, # employee
  is.na(W1_f21500) ~ 2 # not employed
),

eseg = isco08_to_eseg(isco08, work_status = work_status, main_activity = main_activity, age = W1_age, to_factor = FALSE, type = "two-digit", label = FALSE)

)

selects2023panel2$assurance_maladie_franchise_pour = selects2023panel2$assurance_maladie_franchise_pour %>% 
  as.ordered()


selects2023panel2 = selects2023panel2 %>% 
  mutate(
     eseg9 = case_when(
       eseg %in% c(1.1, 1.2, 1.3, 1.4) ~ "Managers",
       eseg %in% c(2.1, 2.2, 2.3, 2.4, 2.5) ~ "Professionals",
       eseg %in% c(3.1, 3.2, 3.3, 3.4, 3.5) ~ "Technicians and associated professionals employees",
       eseg %in% c(4.1, 4.2, 4.3) ~ "small entrepreneurs",
       eseg %in% c(5.1, 5.2, 5.3, 5.4) ~ "Clerks and skilled service employees",
       eseg %in% c(6.1, 6.2, 6.3, 6.4, 6.5) ~ "Skilled industrial employees",
       eseg %in% c(7.1, 7.2, 7.3, 7.4) ~ "Lower status employees",
       eseg %in% c(8.8) ~ "Retired",
       eseg %in% c(9.1) ~ "Student",
       eseg %in% c(9.2, 9.3) ~ "Unemployed or disabled"
     ),
     
     eseg10 = case_when(
       eseg %in% c(1.1, 1.2, 1.3, 1.4) ~ "Managers",
       eseg %in% c(2.1, 2.2, 2.4, 2.5) ~ "Professionals",
       eseg == 2.3 ~ "Business and administration professionals",
       eseg %in% c(3.1, 3.2, 3.3, 3.4, 3.5) ~ "Technicians and associated professionals employees",
       eseg %in% c(4.1, 4.2, 4.3) ~ "small entrepreneurs",
       eseg %in% c(5.1, 5.2, 5.3, 5.4) ~ "Clerks and skilled service employees",
       eseg %in% c(6.1, 6.2, 6.3, 6.4, 6.5) ~ "Skilled industrial employees",
       eseg %in% c(7.1, 7.2, 7.3, 7.4) ~ "Lower status employees",
       eseg %in% c(8.8) ~ "Retired",
       eseg %in% c(9.1) ~ "Student",
       eseg %in% c(9.2, 9.3) ~ "Unemployed or disabled"
     ),
     
     contre_augm_franch_min = if_else(assurance_maladie_franchise_pour %in% c(1, 2), 1,
                                      if_else(is.na(assurance_maladie_franchise_pour), NA, 0))
  )

selects2023panel2 %>% 
  group_by(eseg10) %>% 
  count(assurance_maladie_franchise_pour %in% c(1, 2)) %>% 
  mutate(prop = n/sum(n)) %>% 
  ungroup() %>% 
  filter(`assurance_maladie_franchise_pour %in% c(1, 2)` == TRUE) %>% 
  ggplot(aes(x = prop, y = eseg10))+
  geom_point()
```

```{r model 1 fit}
#| echo: false
#| message: false
#| warning: false

library(MASS)
library(marginaleffects)
selects2023panel2$eseg10 = relevel(factor(selects2023panel2$eseg10), ref = "Business and administration professionals")


data_model_fit = selects2023panel2 %>% 
   dplyr::select(contre_augm_franch_min, eseg10, lr, income_adj_decile, education_ISCED, op_limit_immigration, op_funding_childcare, op_protec_env, op_state_interv, op_social_expenses, op_eu_integration, op_chances_foreigners, op_gender_equality, op_taxes_high_income, op_traditions, op_min_wage, op_incr_retirementAge, probs_vote_plr, probs_vote_centre, probs_vote_ps, probs_vote_udc, probs_vote_verts, probs_vote_vertsliberaux, canton, langue, W1_age, gender) %>% 
  drop_na()

model1 <- glm(data = data_model_fit,
           contre_augm_franch_min ~ eseg10 + lr + income_adj_decile + education_ISCED + op_limit_immigration + op_funding_childcare + op_protec_env + op_state_interv + op_social_expenses + op_eu_integration + op_chances_foreigners + op_gender_equality + op_taxes_high_income + op_traditions + op_min_wage + op_incr_retirementAge + probs_vote_plr + probs_vote_centre + probs_vote_ps + probs_vote_udc + probs_vote_verts + probs_vote_vertsliberaux + canton + langue + W1_age + gender, family = binomial(link = "logit"))

#model1_step = stepAIC(model1)

model1_step2 = glm(formula = contre_augm_franch_min ~ income_adj_decile + op_limit_immigration + 
    op_protec_env + op_social_expenses + op_eu_integration + 
    op_chances_foreigners + op_gender_equality + op_taxes_high_income + 
    op_min_wage + op_incr_retirementAge + probs_vote_centre + 
    probs_vote_ps + probs_vote_verts + probs_vote_vertsliberaux + 
    langue + W1_age + gender, family = binomial(link = "logit"), 
    data = data_model_fit)


#----------------------------------------------------------------------------------------------------------------------------------------#


## model diagnostic

library(performance)
model1_performance = model_performance(model1_step2) 
```

```{r model 1 quantities of interest}
#| echo: false
#| message: false
#| warning: false

avg_slopes_tbl_model1 <- 
model1_step2 %>% 
  avg_slopes()

avg_slopes_tbl_model1 <- 
  avg_slopes_tbl_model1 %>% 
  mutate(
    stars = case_when(
      p.value <= 0.001 ~ "***",
      p.value <= 0.01 ~ "**",
      p.value <= 0.05 ~ "*",
      p.value <= 0.1 ~ "+",
      p.value > 0.1 ~ ""
    )
  )

cbind(avg_slopes_tbl_model1, model1_performance)

library(gt)
tbl_model1 <- 
avg_slopes_tbl_model1 %>% 
  gt() %>% 
  fmt_number(
    decimals = 4
  ) %>% 
  cols_merge(columns = c("estimate", "std.error", "stars"),
             pattern = "<<{1}{3}<br>({2})>>") %>% 
  tab_header(
    title = "Résultats: opinion sur l'augmentation de la franchise minimum",
    subtitle = "Effets et contrastes marginaux moyens prédits par le modèle"
  ) %>% 
  tab_source_note(
    source_note = md(
      paste0(
        "**R² Tjur** = ", round(model1_performance$R2, 3), "<br>",
        "**RMSE** = ", round(model1_performance$RMSE, 3), "<br>",
        "**N** = ", nrow(data_model_fit)
      )
    )
  ) %>% 
  tab_source_note(
    source_note = "+ p < 0.10, * p < 0.05, ** p < 0.01, *** p < 0.01"
  ) 

#tbl_model1 %>% 
    #gtsave(filename = "tbl_model1.png")

tbl_model1

```



## Selects Panel Wave 4 (Premium relief initiative)


```{r selects panel for wave 4 setup}
library(haven)
library(tidyverse)
library(marginaleffects)
library(sjlabelled)
library(DIGCLASS)


# function to recode party satisfaction variables to put "don't know" as middle value

recode_party_satisfaction = function(var){
  new_var = case_when(
    var == 1 ~ 1,
    var == 2 ~ 2, 
    var == 8 ~ 3, 
    var == 3 ~ 4,
    var == 4 ~ 5
  )
}


selects2023panelW4 <-  read_sav("data/selects2023panelW4/data/2626_Selects2023_Panel_Data_v2.0.sav")

selects2023panelW4$isco08 = selects2023panelW4$W1_4_f21601_2dig*100

selects2023panelW4_2 = selects2023panelW4  %>% 
  rename(
    vote_choice = "W4_f10851main6",
    feelings_udc = 'W4_f14177a',
    feelings_ps = 'W4_f14177b',
    feelings_centre = 'W4_f14177c',
    feelings_plr = 'W4_f14177d',
    feelings_verts = 'W4_f14177e',
    feelings_vertslib = 'W4_f14177f',
    
    op_gender_equality = 'W4_f15475',
    op_state_intervention = 'W4_f15435', # 5 = for more competition
    op_2many_worries_abt_env_vs_prices = 'W4_f15478',
    op_min_wage = 'W4_f15815', # 4 = strongly in favor
    op_incr_retirement_age = 'W4_f15811',
    op_foreigners_votingrights = 'W4_f15816',
    op_rights_samesex_couples = 'W4_f15817'
    
    
    
  ) %>% 
  mutate(
    income = case_when(
  W4_f28910 == 1  ~ (0+2000)/2,
  W4_f28910 == 2  ~ (2001+3000)/2,
  W4_f28910 == 3  ~ (3001+4000)/2,
  W4_f28910 == 4  ~ (4001+5000)/2,
  W4_f28910 == 5  ~ (5001+6000)/2,
  W4_f28910 == 6  ~ (6001+7000)/2,
  W4_f28910 == 7  ~ (7001+8000)/2,
  W4_f28910 == 8  ~ (8001+9000)/2,
  W4_f28910 == 9  ~ (9001+10000)/2,
  W4_f28910 == 10 ~ (10001+11000)/2,
  W4_f28910 == 11 ~ (11001+12000)/2,
  W4_f28910 == 12 ~ (12001+13000)/2,
  W4_f28910 == 13 ~ (13001+14000)/2,
  W4_f28910 == 14 ~ (14001+15000)/2,
  W4_f28910 == 15 ~ (15001+16000)/2,
  W4_f28910 == 16 ~ (16001+17000)/2,
  W4_f28910 == 17 ~ (17001+18000)/2,
  W4_f28910 == 18 ~ (18001+19000)/2,
  W4_f28910 == 19 ~ (19001+20000)/2,
  W4_f28910 == 20 ~ 20001         
),

language = factor(as_label(W4_langint)),
gender = factor(as_label(W4_sex)),

rec_satisf_plr = recode_party_satisfaction(W4_f13743a),
rec_satisf_centre = recode_party_satisfaction(W4_f13743b),
rec_satisf_ps = recode_party_satisfaction(W4_f13743c),
rec_satisf_udc = recode_party_satisfaction(W4_f13743d),
rec_satisf_verts = recode_party_satisfaction(W4_f13743e),

income_decile = ntile(income, n = 10),
income_adjusted = income/sqrt(W4_f20500), # W4_f20500 = household size, including R
income_adj_decile = ntile(income_adjusted, n = 10),

lr = if_else(W4_f15200 == 98 | is.na(W4_f15200), NA, W4_f15200),

education_ISCED = case_when(
  W4_f21310rec %in% c(1, 2) ~ 1,  # No education, Primary = ISCED 1
  W4_f21310rec == 3        ~ 2,  # Secondary school = ISCED 2
  W4_f21310rec %in% c(4,5) ~ 3,  # Basic vocational training, apprenticeship = ISC4D 3
  W4_f21310rec %in% c(6,7,8) ~ 4, # Upper secondary specialized, tra4e, vocational = ISCED 4 
  W4_f21310rec == 9 ~ 5,  # Matu = ISCED 5
  W4_f21310rec == 10 ~ 5,  # Higher vocational education with federal dip4oma = ISCED 5
  W4_f21310rec == 11 ~ 6,  # College of higher education = ISCED 6
  W4_f21310rec == 12 ~ 6,  # Uni of applied sciences = ISCED 6 (Ba4helor level)
  W4_f21310rec == 13 ~ 7,  # University / Federal Institute of Tec4nology = ISCED 7 (Master)
  W4_f21310rec == 14 ~ NA   # other
),

public_sector = if_else(W1_4_f21700 == 2, 1, 0),
canton = as_character(W4_canton_sample),
langue = relevel(factor(as_character(W4_langint)), ref = "German"),

#isco08_4d = isco08_swap(W1_ISCO08prof_2dig, from = 2, to = 3),

main_activity = case_when(
  
  # comme il s'agit de la 4eme vague, la question si la situation de travail a changé doit etre prise en compte, si W4_f21300 == 0, la situation n'a pas changé depuis vague 1 (W1)
  W4_f21300 == 0 & W1_f21400 %in% c(1, 2, 7) ~ 1, # working
  W4_f21300 == 0 & W1_f21400 %in% c(3) ~ 2, # in training/education
  W4_f21300 == 0 & W1_f21400 %in% c(6) ~ 3, # disability
  W4_f21300 == 0 & W1_f21400 %in% c(4, 8) ~ 4, # no paid work
  W4_f21300 == 0 & W1_f21400 %in% c(5) ~ 5, # retired
  
  W4_f21300 == 1 & W4_f21400 %in% c(1, 2, 7) ~ 1, # working
  W4_f21300 == 1 & W4_f21400 %in% c(3) ~ 2, # in training/education
  W4_f21300 == 1 & W4_f21400 %in% c(6) ~ 3, # disability
  W4_f21300 == 1 & W4_f21400 %in% c(4, 8) ~ 4, # no paid work
  W4_f21300 == 1 & W4_f21400 %in% c(5) ~ 5 # retired
  
),

# Prise en compte du changement depuis W1, comme pour main_activity
work_status = case_when(
  W4_f21300 == 0 & W1_f21500 == 4 ~ 1, # self-employed
  W4_f21300 == 0 & W1_f21500 %in% c(1, 2, 3) ~ 0, # employee
  W4_f21300 == 0 & is.na(W1_f21500) ~ 2, # not employed
  
  W4_f21300 == 1 & W4_f21500 == 4 ~ 1, # self-employed
  W4_f21300 == 1 & W4_f21500 %in% c(1, 2, 3) ~ 0, # employee
  W4_f21300 == 1 & is.na(W4_f21500) ~ 2 # not employed
),


main_activity2 = case_when(
  
  W1_4_f21400 %in% c(1, 2, 7) ~ 1, # working
  W1_4_f21400 %in% c(3) ~ 2, # in training/education
  W1_4_f21400 %in% c(6) ~ 3, # disability
  W1_4_f21400 %in% c(4, 8) ~ 4, # no paid work
  W1_4_f21400 %in% c(5) ~ 5 # retired
  
),

work_status2 = case_when(
  W1_4_f21500 == 4 ~ 1, # self-employed
  W1_4_f21500 %in% c(1, 2, 3) ~ 0, # employee
  is.na(W1_4_f21500) ~ 2 # not employed
),


eseg = isco08_to_eseg(isco08, work_status = work_status2, main_activity = main_activity2, age = W4_age, to_factor = FALSE, type = "two-digit", label = FALSE),

yes_premium_initiative = if_else(W4_f10771a == 1, 1,
                                 if_else(is.na(W4_f10771a), NA, 0)),

yes_biodiversity_initiative =  if_else(W4_f10751a == 1, 1,
                                 if_else(is.na(W4_f10751a), NA, 0)),

yes_pension_reform = if_else(W4_f10751b == 1, 1,
                                 if_else(is.na(W4_f10751b), NA, 0)),

yes_13th_pension_payment = if_else(W4_f10791 == 1, 1,
                                 if_else(is.na(W4_f10791), NA, 0)),

  
)


selects2023panelW4_2 = selects2023panelW4_2 %>% 
  mutate(
     eseg9 = case_when(
       eseg %in% c(1.1, 1.2, 1.3, 1.4) ~ "Managers",
       eseg %in% c(2.1, 2.2, 2.3, 2.4, 2.5) ~ "Professionals",
       eseg %in% c(3.1, 3.2, 3.3, 3.4, 3.5) ~ "Technicians and associated professionals employees",
       eseg %in% c(4.1, 4.2, 4.3) ~ "small entrepreneurs",
       eseg %in% c(5.1, 5.2, 5.3, 5.4) ~ "Clerks and skilled service employees",
       eseg %in% c(6.1, 6.2, 6.3, 6.4, 6.5) ~ "Skilled industrial employees",
       eseg %in% c(7.1, 7.2, 7.3, 7.4) ~ "Lower status employees",
       eseg %in% c(8.8) ~ "Retired",
       eseg %in% c(9.1) ~ "Student",
       eseg %in% c(9.2, 9.3) ~ "Unemployed or disabled"
     ),
     
     eseg10 = case_when(
       eseg %in% c(1.1, 1.2, 1.3, 1.4) ~ "Managers",
       eseg %in% c(2.1, 2.2, 2.4, 2.5) ~ "Professionals",
       eseg == 2.3 ~ "Business and administration professionals",
       eseg %in% c(3.1, 3.2, 3.3, 3.4, 3.5) ~ "Technicians and associated professionals employees",
       eseg %in% c(4.1, 4.2, 4.3) ~ "small entrepreneurs",
       eseg %in% c(5.1, 5.2, 5.3, 5.4) ~ "Clerks and skilled service employees",
       eseg %in% c(6.1, 6.2, 6.3, 6.4, 6.5) ~ "Skilled industrial employees",
       eseg %in% c(7.1, 7.2, 7.3, 7.4) ~ "Lower status employees",
       eseg %in% c(8.8) ~ "Retired",
       eseg %in% c(9.1) ~ "Student",
       eseg %in% c(9.2, 9.3) ~ "Unemployed or disabled"
     )
  )

selects2023panelW4_2$eseg9 = relevel(as.factor(selects2023panelW4_2$eseg9), ref = "Managers")
selects2023panelW4_2$eseg10 = relevel(as.factor(selects2023panelW4_2$eseg10), ref = "Business and administration professionals")

# Schema de classe oesch

# W4_f21300: Has R's professional situation changed in the past 12 months (e.g. new job, retirement, unemployment)

# W1_4_f21500: R's current position at work, W1 updated with W4


# W4_f21400: R's current working situation, if change in professional situation

# W4_f21500: R's current position at work, if change in professional situation

# W4_f21550: Number of persons employed at company, including R, if change in professional situation

# W4_f21550_W1self: Asked to self-employed from W1 if no change in professional situation: number of persons employed at company, including R

selects2023panelW4_2 <- selects2023panelW4_2 %>% 
  mutate(
    
    self_employed = case_when(
      W1_4_f21500 == 4 ~ 1, # self employed
      W1_4_f21500 %in% c(1, 2, 3) ~ 0 # employee
    ),
    
    n_employees = case_when(
      W4_f21300 == 0 ~ W4_f21550_W1self,
      W4_f21300 == 1 ~ W4_f21550
    ),
    
    oesch8 = isco08_to_oesch(W1_4_f21601_2dig*100, self_employed = self_employed, n_employees = n_employees, n_classes = 8, to_factor = T, label = T)
    
  )

selects2023panelW4_2$vote_choice = factor(as_label(selects2023panelW4_2$vote_choice))


```


```{r premium initiative analysis}
library(lme4)
library(marginaleffects)
library(tidyverse)

data_model_fit2 = selects2023panelW4_2 %>% 
  dplyr::select(yes_premium_initiative, eseg10, income_adj_decile, education_ISCED, lr, op_state_intervention, op_2many_worries_abt_env_vs_prices, op_min_wage, op_incr_retirement_age, op_foreigners_votingrights, vote_choice, gender, W4_age, language, canton) %>% 
  drop_na()





model_glm1 = glm(data = data_model_fit2,
                 yes_premium_initiative ~ income_adj_decile + education_ISCED + eseg10 + lr + op_state_intervention + op_2many_worries_abt_env_vs_prices + op_min_wage + op_incr_retirement_age + op_foreigners_votingrights + vote_choice + gender + W4_age + language + canton,
                  family = binomial(link = "logit"))

#best_model_glm1 = stepAIC(model_glm1)

best_model_glm2 = glm(formula = yes_premium_initiative ~ income_adj_decile + I(eseg10 == "Retired") + lr + op_state_intervention + op_2many_worries_abt_env_vs_prices + op_min_wage + op_incr_retirement_age + op_foreigners_votingrights + vote_choice + gender + W4_age + language, family = binomial(link = "logit"), 
                      data = data_model_fit2)

avg_slopes_tbl_bestmodelW4 = best_model_glm2 %>% 
  avg_slopes() %>% 
  drop_na()

```

```{r premium initiative model diagnostics and final table}
library(performance)

model2_performance = model_performance(best_model_glm2)

avg_slopes_tbl_bestmodelW4 <- 
  avg_slopes_tbl_bestmodelW4 %>% 
  mutate(
    stars = case_when(
      p.value <= 0.001 ~ "***",
      p.value <= 0.01 ~ "**",
      p.value <= 0.05 ~ "*",
      p.value <= 0.1 ~ "+",
      p.value > 0.1 ~ ""
    )
  )


tbl_model2 <- 
avg_slopes_tbl_bestmodelW4 %>% 
  gt() %>% 
  fmt_number(
    decimals = 4
  ) %>% 
  cols_merge(columns = c("estimate", "std.error", "stars"),
             pattern = "<<{1}{3}<br>({2})>>") %>% 
  tab_header(
    title = "Résultats: vote sur l'initiative d'allègement des primes",
    subtitle = "Effets et contrastes marginaux moyens prédits par le modèle"
  ) %>% 
  tab_source_note(
    source_note = md(
      paste0(
        "**R² Tjur** = ", round(model2_performance$R2, 3), "<br>",
        "**RMSE** = ", round(model2_performance$RMSE, 3), "<br>",
        "**N** = ", nrow(data_model_fit)
      )
    )
  ) %>% 
  tab_source_note(
    source_note = "+ p < 0.10, * p < 0.05, ** p < 0.01, *** p < 0.01"
  ) %>% 
  text_replace(
    pattern = "^W4_age$",
    replacement = "Âge"
  ) %>% 
  text_replace(
    pattern = "^eseg10$",
    replacement = "Catégorie socio-professionnelle"
  ) %>% 
  text_replace(
    pattern = "^gender$",
    replacement = "Genre"
  ) %>% 
  text_replace(
    pattern = "^income_adj_decile$",
    replacement = "Décile du revenu ajusté du ménage"
  ) %>% 
  text_replace(
    pattern = "^language$",
    replacement = "Langue"
  ) %>% 
  text_replace(
    pattern = "^lr$",
    replacement = "Auto-positionnement gauche-droite"
  ) %>% 
  text_replace(
    pattern = "^op_2many_worries_abt_env_vs_prices$",
    replacement = "Opinion: Trop de préoccupation pour l'environnement par rapport aux coûts et aux prix"
  ) %>% 
  text_replace(
    pattern = "^op_foreigners_votingrights$",
    replacement = "Opinion: pour le droit de vote aux étrangers"
  ) %>% 
  text_replace(
    pattern = "^op_incr_retirement_age$",
    replacement = "Opinion: augmenter l'âge du départ à la retraite"
  ) %>% 
  text_replace(
    pattern = "^op_min_wage$",
    replacement = "Opinion: augmenter le salaire minimum"
  ) %>% 
  text_replace(
    pattern = "^op_state_intervention$",
    replacement = "Opinion: État vs marché et concurrence"
  ) %>% 
  text_replace(
    pattern = "^vote_choice$",
    replacement = "Vote si élections ce dimanche"
  )
  


#tbl_model2 %>% 
 #   gtsave(filename = "tbl_model2.tex")


tbl_model2

```

```{r model franchise checks}
#| fig-height: 10
#| fig-width: 10
library(performance)

check_model(model1_step2)
```

```{r model premium checks}
#| fig-height: 10
#| fig-width: 10
check_model(best_model_glm2)
```









